[package]
name = "fli-tool"
description = "A tiny tool that lists information about files"
version = "0.1.4"
edition = "2024"
license = "MIT"
repository = "https://github.com/tracyspacy/fli"
readme = "README.md"
categories = ["command-line-utilities"]
keywords = ["ls","cli","terminal","no-std"]

[profile.dev]
panic = "abort"
lto = "thin"
opt-level = 1

[[bin]]
name = "fli"
path = "src/main.rs"

[profile.release]
panic = "abort"
opt-level = "z" #"s"
lto = true
codegen-units = 1
strip = true

[dependencies]
libc = {version="0.2.186", default-features = false }
