[target.arm-unknown-linux-gnueabihf]
linker = "arm-unknown-linux-gnueabihf-gcc"
rustflags = [
    "-C", "panic=abort",
    "-C", "link-arg=-lgcc_s",
    "-C", "opt-level=z"
]
[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"
rustflags = [
    "-C", "panic=abort",
    "-C", "link-arg=-lgcc_s",
    "-C", "opt-level=z"
]
[target.x86_64-unknown-linux-musl]
linker = "x86_64-linux-musl-gcc"
rustflags = [
    "-C", "panic=abort",
    "-C", "opt-level=z",
    #"-C", "link-arg=-lc",
    # dynamically linked
    "-C", "target-feature=-crt-static",
]
